name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install SSH client
      run: sudo apt-get update && sudo apt-get install -y openssh-client

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t yourusername/my_app:latest .
        docker push yourusername/my_app:latest

    - name: Copy files via SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > key.pem
        chmod 600 key.pem
        rsync -avz -e "ssh -i key.pem -o StrictHostKeyChecking=no" ./app/ jwyatt@192.168.0.220:/home/jwyatt/service-dashboard/app/
        rsync -avz -e "ssh -i key.pem -o StrictHostKeyChecking=no" docker-compose.yml jwyatt@192.168.0.220:/home/jwyatt/service-dashboard/docker-compose.yml

    - name: Restart Docker container
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        ssh -i key.pem -o StrictHostKeyChecking=no jwyatt@192.168.0.220 << 'EOF'
          cd /home/jwyatt/service-dashboard
          docker-compose down
          docker-compose build
          docker-compose up -d
        EOF
